
name: Push to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit 0
    - name: Build Docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.LIFEOMIC_DOCKERHUB_USERNAME }}
        password: ${{ secrets.LIFEOMIC_DOCKERHUB_TOKEN }}
        repository: lifeomic/foundation-ingest
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false