
name: Push to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exit if not on master branch
      if: endsWith(github.ref, 'master') == false
      run: exit 0
    - name: Build Docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lifeomic/foundation-ingest
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}